[package]
name = "bootstrapper"
version = "0.0.0"
edition = "2021"
license = "MIT"
description = "A Dockerfile generator that assembles a linux distribution from scratch"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
