name: Rust

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  assemble:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Docker Layer Caching
        uses: satackey/action-docker-layer-caching@v0.0.11      
        continue-on-error: true
        with:
          key: docker-cache-v3-{hash}
          restore-keys: |
            docker-cache-v3-
      - name: Run
        run: cargo run --bin=assemble -- `cat ci-build.txt`
  depgraph:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run
        run: cargo run --bin=depgraph -- `cat ci-build.txt` | tee deps.dot
      - name: Setup Graphviz
        uses: ts-graphviz/setup-graphviz@v1
      - name: Generate PNG
        run: dot deps.dot -Tpng > deps.png
      - name: Generate SVG
        run: dot deps.dot -Tsvg > deps.svg
      - uses: hkusu/s3-upload-action@v2
        name: Upload PNG to S3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-west-2'
          aws-bucket: ${{ secrets.AWS_BUCKET }}
          file-path: 'deps.png'
          destination-dir: '/'
          bucket-root: '/'
          content-type: 'image/png'
      - uses: hkusu/s3-upload-action@v2
        name: Upload SVG to S3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-west-2'
          aws-bucket: ${{ secrets.AWS_BUCKET }}
          file-path: 'deps.svg'
          destination-dir: '/'
          bucket-root: '/'
          content-type: 'image/svg+xml'
